# Generated by Django 3.1.1 on 2020-12-01 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_created=True)),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('describe', models.TextField(default='')),
                ('status', models.BooleanField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.project')),
            ],
        ),
    ]
